[tool.black]
line-length = 88
exclude = '''
/(
    \.venv
    | \.ipynb_checkpoints
    | legacy
    | venv
    | \.venv
    | venv
    | \.venv
)/
'''

[tool.ruff]
line-length = 88
target-version = "py310"
exclude = [
    ".venv",
    "venv",
    ".ipynb_checkpoints",
    "legacy",
]
ignore = ["E501"]

[tool.mypy]
check_untyped_defs = true

[tool.setup]
name = "rfm-clustering-pca-kmeans"
version = "0.1.0"
description = ""
author = "Jorge Trivilin"
author_email = "jorge.trivilin@gmail.com"
